services:
hytale-server:
  image: deinfreu/hytale-server-container:latest
  container_name: hytale-server
  restart: unless-stopped
  environment:
  EULA: "TRUE"
  DEBUG: "FALSE"
  ports:
    - "5520:5520/udp"
  volumes:
    - ./data:/home/container
