services:
  immich-server:
    container_name: immich_server_1
    image: ghcr.io/immich-app/immich-server:v2.2.3@sha256:4504d794123c3f5410cc45bbc61e4d7dbcacec1e1b0cd2e599691430c94e5849
    volumes:
      # Librer√≠a de fotos de Immich
      - ${APP_DATA_DIR}/data/upload:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: immich
      DB_PASSWORD: moneyprintergobrrr
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: log
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: "false"
      REVERSE_GEOCODING_PRECISION: "3"
      PUBLIC_LOGIN_PAGE_MESSAGE: ""
    ports:
      - "2283:2283"
    depends_on:
      - immich-redis
      - immich-postgres
    restart: on-failure
    devices:
      - /dev/dri

  immich-machine-learning:
    container_name: immich_machine-learning_1
    image: ghcr.io/immich-app/immich-machine-learning:v2.2.3
    volumes:
      - ${APP_DATA_DIR}/data/model-cache:/cache
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: immich
      DB_PASSWORD: moneyprintergobrrr
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: log
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: "false"
      REVERSE_GEOCODING_PRECISION: "3"
      PUBLIC_LOGIN_PAGE_MESSAGE: ""
      IMMICH_MACHINE_LEARNING_URL: http://immich_machine-learning_1:3003
    restart: on-failure
    devices:
      - /dev/dri

  immich-redis:
    container_name: immich_redis_1
    image: valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    devices:
      - /dev/dri

  immich-postgres:
    container_name: immich_postgres_1
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: immich
      DB_PASSWORD: moneyprintergobrrr
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: log
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: "false"
      REVERSE_GEOCODING_PRECISION: "3"
      PUBLIC_LOGIN_PAGE_MESSAGE: ""
      IMMICH_MACHINE_LEARNING_URL: http://immich_machine-learning_1:3003
      POSTGRES_PASSWORD: moneyprintergobrrr
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    restart: on-failure
    devices:
      - /dev/dri

volumes:
  # Solo lo usa machine-learning, pero lo definimos por claridad
  model-cache:
