name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /data/immich/upload:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOST: immich_postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOST: immich_redis
    ports:
      - "2283:2283"
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /data/immich/cache:/cache
    restart: always
    depends_on:
      - immich_server

  immich_redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8
    restart: always

  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    volumes:
      - /data/immich/db:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
